In [211]:
#первое задание
import numpy as np
y=np.random.random((10,3))

print("Matrix 10x3:")
print(y)
print("\nMinimum element in each row")
z=np.min(abs(y-0.5),1)
z1=z+0.5
z2=0.5-z
mask1=(y[:,0]==z1)+(y[:,1]==z1)+(y[:,2]==z1)#
z2[mask1]=z1[mask1]
print(z2)

Matrix 10x3:
[[0.99605919 0.86591006 0.23779729]
 [0.95447183 0.01164507 0.77537058]
 [0.56781975 0.06798236 0.2927219 ]
 [0.67870438 0.21273    0.74648125]
 [0.84688634 0.18723933 0.39230223]
 [0.64019568 0.8526016  0.79432873]
 [0.02804981 0.21578117 0.67508094]
 [0.32675084 0.90020905 0.04759427]
 [0.64763075 0.54507304 0.55323079]
 [0.67197117 0.22080692 0.28970743]]

Minimum element in each row
[0.23779729 0.77537058 0.56781975 0.67870438 0.39230223 0.64019568
 0.67508094 0.32675084 0.54507304 0.67197117]


In [13]:
#второе задание
import numpy as np
y=np.random.random((6,6))
print("Matrix 6x6")
print(y)
print("\n ")
print((np.sum(y,axis=1))/(np.min(y,axis=0)))

Matrix 6x6
[[0.71291824 0.4236434  0.59581764 0.99024092 0.20548557 0.80974547]
 [0.73480759 0.98313365 0.36079337 0.76458754 0.83149797 0.97660874]
 [0.41458986 0.64105914 0.11327269 0.0897238  0.00733294 0.44540153]
 [0.00381657 0.74293964 0.11079265 0.98296018 0.3085668  0.61271104]
 [0.54926153 0.63930532 0.50518707 0.54491641 0.11191982 0.39276662]
 [0.81357848 0.11510959 0.68084533 0.26628811 0.87352305 0.96243309]]

 
[979.3733045   40.40869843  15.44669281  30.7809852  374.11435876
   9.45033882]


In [9]:
#Третье задание
#я считаю, что 6 не стоит перед 0, поэтому в ответе выйдет 5
import numpy as np
x=np.array([6,2,0,3,0,0,5,7,0])
mask =x==0
mask[x.size-1]=False
mask=~np.roll(mask,1)
x[mask]=0
print("The max element, preceded by 0, is "+str(np.max(x))+".")

The max element, preceded by 0, is 5.


In [148]:
#четвертое задание
import numpy as np
x=np.ones(10)
#1 1 1 
i=np.array([0,1,2,3,5,5,5,8])
size=x.size
x +=np.bincount(i, minlength=size)
print(x)


[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]


In [93]:
#Пятое задание
import numpy as np
n=4
a=np.arange(n*n).reshape(n,n)
b=np.array(a).reshape(n*n)

dict1={ }
dict2={ }
dict1.update({0: [0]})
vect=b[n-1::n-1]
dict2.update({n-1:list(vect[:-1])})
for i in range(1,n-1):#я не представляю как здесь можно обойдись без цикла
    dict1.update({i: list(b[i::n-1][:i+1])})
    dict2.update({i+n-1:list(b[i::n-1][i+1:])})

dict2.update({2*n-2: [n*n-1]})
dict1.update(dict2)
print(dict1)

{0: [0], 1: [1, 4], 2: [2, 5, 8], 3: [3, 6, 9, 12], 4: [7, 10, 13], 5: [11, 14], 6: [15]}


In [168]:
#шестое задание функции
import numpy as np
import random
from scipy.spatial.distance import cdist
#описание библиотечной функции whiten 
def whiten (features):
    x=np.array(features)
    b=np.std(x,axis=0)
    x/=b
    return x

#алгоритм kmean
def kmean (obs,k_or_guess,tresh=1e-05):
    var=1.
    distortion=0.
    n=int(obs.size/obs[0].size) 
    k=0
    codebook=np.array
    #здесь я разбираю на случаи
    #когда k_or_guess число
    if type(k_or_guess)==type(k):
        k=k_or_guess
        S=list(np.arange(n))
        random.shuffle(S)
        S=np.array(S)
        codebook=np.array(obs[S[0:k]])
    #когда k_or_guess массив
    else:
        codebook=np.array(k_or_guess)
        k=int(k_or_guess.size/2)
            
    while abs(var-distortion)>tresh:
        distortion=var
        #создание кластера, матрица S хранит индексы индексы  
        S=np.argmin(cdist(obs,codebook),axis=1)
        #поиск центра тяжести для каждого кластера
        for i in range(k):
            K=[]
            for j in range(n):
                if np.any(S[j]==i):
                    K.append(obs[j])
            codebook[i]=np.mean(K,0)
        var=np.std(codebook)
    return (codebook,distortion)

In [169]:
#проверка шестого задания
features = np.array([[ 1.9,2.3],#0
                   [ 1.5,2.5],
                   [ 0.8,0.6],#2
                   [ 0.4,1.8],
                   [ 0.1,0.1],#4
                   [ 0.2,1.8],
                   [ 2.0,0.5],#6
                   [ 0.3,1.5],
                   [ 1.0,1.0]])

whitened=whiten(features)

book=np.array((whitened[0],whitened[2]))

kmean(whitened,book)
#kmeans_export(book, whitened)

(array([[2.45121811, 3.03653641],
        [0.98872663, 1.31944737]]), 0.8296716105153548)

In [170]:
#сравнение шестого задания, 
#если взять библиотечную функцию
#ответ будет почти тот же
from numpy import array
from scipy.cluster.vq import vq, kmeans, whiten
features  = array([[ 1.9,2.3],
                   [ 1.5,2.5],
                   [ 0.8,0.6],
                   [ 0.4,1.8],
                   [ 0.1,0.1],
                   [ 0.2,1.8],
                   [ 2.0,0.5],
                   [ 0.3,1.5],
                   [ 1.0,1.0]])
whitened = whiten(features)
book = array((whitened[0],whitened[2]))
kmeans(whitened,book)

(array([[2.45121811, 3.03653641],
        [0.98872663, 1.31944737]]), 0.9088234961964715)

In [166]:
#здесь вызвана библиотечная функция алгоритма kmeans
from numpy import random
random.seed((1000,2000))
codes = 3
kmeans(whitened,codes)

(array([[1.40584568, 0.69587293],
        [2.45121811, 3.03653641],
        [0.4325679 , 2.15087996]]), 0.5511808116483707)

In [167]:
#здесь вызван алгоритм kmean, написанная мною
#ответы отличаются,потому что были взяты разные центроиды
from numpy import random
random.seed((1000,2000))
codes = 3
kmean(whitened,codes)

(array([[0.4325679 , 2.15087996],
        [0.9131989 , 0.71695999],
        [2.59540741, 2.23522819]]), 0.8426836939712384)