In [2]:
#первое задание
import numpy as np
y=np.random.random((10,3))

def fun1(x):
    size = int(x.size/x[0].size)
    vector=fun2(x[0])
    for i in range(1,size):
        vector=np.vstack((vector,fun2(x[i])))
    return vector
def fun2(x):
    size=int(x.size)
    min=0.5
    imin=-1
    for i in range(size):
        t=abs(0.5-x[i])
        if t<min:
            min=t
            imin=i
    return x[imin]

print("Matrix 10x6:")
print(y)
print("\nMinimum element in each row")
print(fun1(y))


Matrix 10x6:
[[0.42883535 0.74930013 0.4067428 ]
 [0.53856417 0.69466298 0.53103074]
 [0.42704258 0.32459148 0.64910233]
 [0.69282833 0.6147935  0.3375795 ]
 [0.87051944 0.42446066 0.62612296]
 [0.83685775 0.52402982 0.02130434]
 [0.13641435 0.28130642 0.2955729 ]
 [0.67282401 0.5289989  0.54706794]
 [0.92323387 0.46077661 0.36241209]
 [0.13484654 0.34824772 0.31373632]]

Minimum element in each row
[[0.42883535]
 [0.53103074]
 [0.42704258]
 [0.6147935 ]
 [0.42446066]
 [0.52402982]
 [0.2955729 ]
 [0.5289989 ]
 [0.46077661]
 [0.34824772]]


In [6]:
#второе задание
import numpy as np
y=np.random.random((6,6))
res=[]
print("Matrix 6x6")
print(y)
for i in range(6):
    sum=0
    min=y[0][i]
    for j in range(6):
        sum+=y[i][j]
        if(y[j][i]<min):
            min=y[j][i]
    sum/=min
    res.append(sum)
print("\n\n")
for i in range(6):
    print("Сумма "+str(1+i)+" строки,деленной на минимум элемента "+str(i+1)+" столбца : "+str(res[i])+"\n")

Matrix 6x6
[[0.92259362 0.10018718 0.11115743 0.70829888 0.01595894 0.53046588]
 [0.42894989 0.23558267 0.17599439 0.309886   0.92699214 0.81712427]
 [0.58632676 0.72684037 0.95048685 0.32675327 0.71527669 0.03505854]
 [0.43070776 0.46977377 0.16232648 0.20867434 0.63615586 0.24881071]
 [0.13659345 0.59238192 0.31330235 0.78534836 0.67419376 0.65347289]
 [0.09337329 0.75107439 0.6900488  0.71320716 0.93883713 0.49206701]]



Сумма 1 строки,деленной на минимум элемента 1 столбца : 25.581853467932625

Сумма 2 строки,деленной на минимум элемента 2 столбца : 28.891215161515593

Сумма 3 строки,деленной на минимум элемента 3 столбца : 30.054154816261736

Сумма 4 строки,деленной на минимум элемента 4 столбца : 10.334039906505602

Сумма 5 строки,деленной на минимум элемента 5 столбца : 197.71318233284066

Сумма 6 строки,деленной на минимум элемента 6 столбца : 104.9275812937751



In [8]:
#Третье задание
import numpy as np
x=np.array([6,2,0,3,0,0,5,7,0])
maxElement=0
size=x.size
print(x)
for i in range(1,size):
    if x[i-1]==0:
        if x[i]>maxElement:
            maxElement=x[i]
print("The max element, preceded by 0, is "+str(maxElement)+".")

[6 2 0 3 0 0 5 7 0]
The max element, preceded by 0, is 5.


In [12]:
#четвертое задание
import numpy as np
x=np.ones(10)
i=np.array([0,1,2,3,5,5,5,8])
size=i.size
for j in range(size):
    x[i[j]]+=1
print(x)

[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]


In [30]:
#Пятое задание
import numpy as np
n=4
a=np.arange(n*n).reshape(n,n)
dict1={}
for i in range(n):
    vect=[]
    for j in range(i+1):
        vect.append(a[j][i-j])
    dict1.update({i:vect})
for i in range(1,n):
    vect=[]
    for j in range(n-i):
        vect.append(a[i+j][n-1-j])
    dict1.update({n+i-1:vect})
print(dict1)

{0: [0], 1: [1, 4], 2: [2, 5, 8], 3: [3, 6, 9, 12], 4: [7, 10, 13], 5: [11, 14], 6: [15]}


In [7]:
#шестое задание функции
import numpy as np
import random
#описание библиотечной функции whiten 
def whiten (features):
    x=np.array(features)
    b=np.std(x,axis=0)
    size=int(x.size/x[0].size)
    for i in range(size):
        x[i]/=b
    return x

#вычисляет расстояние между двумя точками
def dist (x ,y):
    n=x.size
    res=0
    for i in range(n):
        res+=(x[i]-y[i])**2
    return res**(0.5)
#создает кластеры
def creatCluster(x,centroid,S):
    k=int(centroid.size/centroid[0].size)
    n=int(x.size/x[0].size)
    for i in range(n):#пробегает по всем х
        index=0
        minDistation=dist(x[i],centroid[0])
        for j in range(1,k):#пробегает по всем centroid
            dist2=dist(x[i],centroid[j])
            if dist2<minDistation:
                index=j
                minDistation=dist2
        S.append(index)
#ищет центры тяжести
def centerOfGravity(x,centroid,S):
    k=int(centroid.size/centroid[0].size)
    n=int(x.size/x[0].size)
    for i in range(k):
        rx=0.0
        ry=0.0
        sumK=0.0
        for j in range(n):
            if S[j]==i:
                rx+=x[j][0]
                ry+=x[j][1]
                sumK+=1.0
        if sumK==0:
            rx=0
            ry=0
        else:
            rx=rx/sumK
            ry=ry/sumK
        centroid[i][0]=rx
        centroid[i][1]=ry
#отклонение
def variation(x,y):
    n=int(x.size/x[0].size)
    res=0.0
    for i in range(n):
        res+=dist(x[i],y[i])
    return res
#алгоритм kmean
def kmean (obs,k_or_guess,tresh=1e-05):
    var=1.
    distortion=1.
    n=int(obs.size/obs[0].size) 
    k=0
    codebook=np.array

    if type(k_or_guess)==type(k):
        k=k_or_guess
        S=[]
        for i in range(n):
            S.append(i)
        random.shuffle(S)
        codebook=np.array(obs[S[0]])
        for i in range(1,k):
            codebook=np.vstack((codebook,obs[S[i]]))
    else:
        codebook=np.array(k_or_guess)
        k=int(k_or_guess.size/k_or_guess[0].size)
            
    while var>tresh:
        distortion=var
        S=[]
        #нужно сделать кластер
        creatCluster(obs,codebook,S)
        #поиск центра тяжести
        copy=np.array(codebook)
        centerOfGravity(obs,codebook,S)
        var=variation(copy,codebook)
    return (codebook,distortion)


In [8]:
#проверка шестого задания
features = np.array([[ 1.9,2.3],#0
                   [ 1.5,2.5],
                   [ 0.8,0.6],#2
                   [ 0.4,1.8],
                   [ 0.1,0.1],#4
                   [ 0.2,1.8],
                   [ 2.0,0.5],#6
                   [ 0.3,1.5],
                   [ 1.0,1.0]])

whitened=whiten(features)

book=np.array((whitened[0],whitened[2]))

kmean(whitened,book)

(array([[2.45121811, 3.03653641],
        [0.98872663, 1.31944737]]), 0.8989556585890871)

In [5]:
#сравнение шестого задания, 
#если взять библиотечную функцию
#ответ будет почти тот же
from numpy import array
from scipy.cluster.vq import vq, kmeans, whiten
features  = array([[ 1.9,2.3],
                   [ 1.5,2.5],
                   [ 0.8,0.6],
                   [ 0.4,1.8],
                   [ 0.1,0.1],
                   [ 0.2,1.8],
                   [ 2.0,0.5],
                   [ 0.3,1.5],
                   [ 1.0,1.0]])
whitened = whiten(features)
book = array((whitened[0],whitened[2]))
kmeans(whitened,book)

(array([[2.45121811, 3.03653641],
        [0.98872663, 1.31944737]]), 0.9088234961964715)

In [6]:
#здесь вызвана библиотечная функция алгоритма kmeans
from numpy import random
random.seed((1000,2000))
codes = 3
kmeans(whitened,codes)

(array([[1.40584568, 0.69587293],
        [2.45121811, 3.03653641],
        [0.4325679 , 2.15087996]]), 0.5511808116483707)

In [9]:
#здесь вызван алгоритм kmean, написанная мною
#ответы отличаются,потому что были взяты разные центроиды
from numpy import random
random.seed((1000,2000))
codes = 3
kmean(whitened,codes)

(array([[0.4325679 , 2.15087996],
        [0.9131989 , 0.71695999],
        [2.59540741, 2.23522819]]), 0.9959647282285382)